name: CI

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
jobs:
    ci:
      strategy:
        matrix:
          os: 
            - ubuntu-latest
            - windows-latest
            - macos-latest
          version: ['3.8', '3.9', '3.10', '3.11']
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.version }}
        - name: Install poetry
          uses: abatilo/actions-poetry@v2
        - uses: actions/cache@v3
          name: Define a cache for the virtual environment based on the dependencies lock file
          with:
            path: ./.venv
            key: venv-${{ hashFiles('poetry.lock') }}
        - name: Install the project dependencies
          run: poetry install
        - name: Run the automated tests (for example)
          run: poetry run python -m unittest