name: Docs publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry env use "3.8"
          poetry install

      - name: Build 📚
        run: poetry run portray as_html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
            branch: gh-pages
            folder: site
            clean: true
            single-commit: true