name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Run image
      uses: abatilo/actions-poetry@v2
    
    - name: Install dependencies
      run: |
        rm -f poetry.lock
        poetry install
    
    - name: Sphinx APIDoc
      run: |
        poetry run sphinx-apidoc -f -o jupyter-book/_api/ ai2_kit/ --separate

    # Build the book
    - name: Build the book
      run: |
        poetry run jupyter-book build jupyter-book/

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: jupyter-book/_build/html